### ISSUE TITLE
aarch64 Support

### ISSUE THREAD

**Issue by zcobell** [conda-forge/ecflow-feedstock#58]
### Comment:

Hello ecflow development team - 

Recently, we've been working to deploy ecflow within ARM HPC systems on AWS systems for hurricane storm surge forecasting workflows. 

Building the code from source seems to work well on the ARM architecture using the GCC compilers. Would it be possible to enable the aarch64 target within this feedstock? I tinkered with the `conda-forge.yaml` and it looks like it just needs:

```yaml
provider:
   linux_aarch64: default
```

I'm happy to submit a pull request, but didn't want to set off anything if it wasn't something this group wanted to support.

Much appreciated!

**Comment by marcosbento** [comment]
We are happy to enable the ecFlow build for aarch64 systems. Please submit the pull request.

Unfortunately, notice that we cannot activetly support these systems as we don't have easy means to reproduce potential issues -- support can only be offered on a best effort basis, without any guarantee.
